kind: Deployment
apiVersion: apps/v1
metadata:
  name: boot-app-deployment
  labels:
    app: boot-app
spec:
  replicas: 3 #We always want more than 1 replica for HA
  selector:
    matchLabels:
      app: boot-app
  template:
    metadata:
      labels:
        app: boot-app
    spec:
#      initContainers:
#        command: ['sh', '-c', 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://172-17-0-3.default.pod.cluster.local:9122/a-bootiful-client/default)" != "200" ]]; do echo waiting; sleep 5; done']
      containers:
      - name: config-server #1st container
        image: rashjz/config-server:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
          - containerPort: 9122
        env:
          - name: PORT
            value: "9122"
      - name: eureka-server #2st container
        image: rashjz/eureka-server:0.0.1-SNAPSHOT #Dockerhub image
        imagePullPolicy: Always
        ports:
        - containerPort: 8761 #Exposes the port 8761 of the container
        env:
        - name: PORT #Env variable key passed to container that is read by app
          value: "8761" # Value of the env port.
      - name: boot-admin #3nd container
        image: rashjz/boot-admin:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
      - name: boot-app-service #4rd container
        image: rashjz/boot-app-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
        env:
        - name: PORT
          value: "9000"
---
kind: Service
apiVersion: v1
metadata:
  name: boot-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: boot-app
  ports:
  - name: config-server-port
    protocol: TCP
    port: 9122
  - name: eureka-server-port
    protocol: TCP
    port: 8761
  - name: boot-admin-port
    protocol: TCP
    port: 8080
  - name: boot-app-service-port
    protocol: TCP
    port: 9000
